window.tyrano_lang = {
    word: {
        go_title: "要返回到标题画面吗？",
        exit_game: "将关闭窗口并退出游戏。确定吗？",
        not_saved: "还没有保存的数据。",
        confirm: "确认",
        confirm_beforeunload: "有未保存的内容。确定要退出游戏吗？",
        tag: "标签",
        not_exists: "不存在。",
        error: "发生错误。请检查脚本。",
        label: "标签",
        label_double: "在同一剧本文件中重复。",
        error_occurred: "发生错误。",
        save_file_violation_1: "检测到存档数据移动。如果不是可信的存档数据，请绝对不要加载。",
        save_file_violation_2: "要加载存档数据并启动游戏吗？",
        save_file_violation_3: "启动已中止。请删除存档数据后再重新启动。",
        double_start: "游戏已启动。无法二次启动。",
        reload: "重新加载",
        line: "{ line }行目",
        initialized_saved_data: "存档数据已初始化。",
        initializing_saved_data: "正在初始化存档数据。确定吗？",
        saved_data_is_corrupted: "存档数据可能已损坏。要初始化存档数据吗？",
        save_does_not_work: "此环境下存档功能无法工作。通常发生在本地执行时。",
        undefined_tag: "标签「{ name }」不存在。",
        undefined_label: "标签「{ name }」不存在。",
        undefined_character: "指定的角色「{ name }」未定义。请用[chara_new]定义。",
        undefined_face: "指定的角色「{ name }」的表情「{ face }」未定义。请用[chara_face]定义。",
        undefined_character_parts: "指定的角色「{ name }」的差分部件未定义。请用[chara_layer]定义。",
        undefined_keyframe: "指定的关键帧动画「{ keyframe }」未定义。请用[keyframe]定义。",
        undefined_3d_model: "指定的3D模型「{ name }」未定义。",
        preload_failure_sound: "未找到音频文件「{ src }」。是否指定了完整路径？\n\n(示例) ./data/bgm/my_bgm.mp3",
        preload_failure_image: "未找到图像文件「{ src }」。是否指定了完整路径？\n\n(示例) ./data/image/my_image.png",
        preload_failure_video: "未找到视频文件「{ src }」。是否指定了完整路径？\n\n(示例) ./data/video/my_video.mp4",
        invalid_keyframe: "关键帧值无效。",
        invalid_keyframe_percentage: "关键帧中设置的百分比「{ percentage }」无效。请指定为\"0%\"、\"30%\"等。",
        error_in_iscript: "[iscript] 内部发生错误。",
        missing_endif: "在[if]之后未找到[elsif]、[else]或[endif]。或者[if]内的标签数量过多。",
        missing_endmacro: "在[macro]之后未找到[endmacro]。或者[macro]内的标签数量过多。",
        missing_endignore: "在[ignore]之后未找到[endignore]。或者[ignore]内的数量过多。",
        missing_parameter: "标签「{ tag }」需要参数「{ param }」。",
        if_and_endif_do_not_match: "[if]与[endif]的数量不匹配。",
        unsupported_extensions: "文件格式「{ ext }」不支持。",
        undefined_keyconfig: "未定义按键配置。可能是KeyConfig.js不存在或KeyConfig.js中有语法错误。请检查是否缺少逗号\",\"或括号\"]\" \"}\"。",
        compensate_missing_quart: "检测到意外的\"]\"。可能是参数的引号数量不足，已自动修正并解释。\n\n修正前: { before }\n修正后: { after }",
        duplicate_label: "标签「{ name }」在同一剧本文件中重复。请确保标签名在同一剧本文件中不重复。",
        file_not_found: "未找到文件。\n\n{ path }",
        patch_not_found: "未找到补丁文件。\n\n{ path }",
        new_patch_found: "发现新更新。\n\n版本: { version }\n{ message }\n\n要进行更新吗？",
        apply_web_patch: "正在进行更新。完成后，游戏将自动关闭。",
        apply_patch_complete: "更新已应用。请重新启动游戏。",
    },

    novel: {
        file_menu_button_save: "menu_button_save.gif",
        file_menu_button_load: "menu_button_load.gif",
        file_menu_button_message_close: "menu_message_close.gif",
        file_menu_button_skip: "menu_button_skip.gif",
        file_menu_button_title: "menu_button_title.gif",
        file_menu_button_close: "menu_button_close.png",
        file_menu_bg: "menu_bg.jpg",
        file_save_bg: "menu_save_bg.jpg",
        file_load_bg: "menu_load_bg.jpg",
        file_button_menu: "button_menu.png",
        error_occurred: "error occurred",
    },
};
